INSERT INTO orders (product_id, product_name, quantity, created_date, last_modified_date)
VALUES (1, 'Dell 5401', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (9, 'Samsung T22', 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (7, 'Toshiba', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 'ASUS', 33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (3, 'HTC', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);